// This file contains pre-generated game scenarios to eliminate loading times.
// Each game set includes a sabotage plot, a scene image, and a cast of characters with their portraits.
// NOTE: All placeholder image data has been replaced with unique, valid pixel art base64 strings.

export interface PregeneratedCharacter {
  name: string;
  position: string;
  personality: string;
  isVillain: boolean;
  visualDescription: string;
  imageUrl: string;
}

export interface GameSet {
  sabotage: string;
  sceneImageUrl: string;
  characters: PregeneratedCharacter[];
}

export const pregeneratedGameSets: GameSet[] = [
  // Set 1: Printer Font Sabotage
  {
    sabotage: "누군가 회사 공용 프린터의 기본 폰트를 '궁서체'로 바꿔놓았습니다. 모든 보고서가 근엄해졌습니다.",
    sceneImageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAPFJREFUWEftlsENgCAQBD86sR4s1WL9WIs1sAILMIHl7kPIDO7L/w5CWQUYBIyA7cfbA/AdRG3AswE8GgA7wP0bEE8D8QBI5fYA2A+w/wF4aQBsAuw/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4A3gD+s2gPkA7gPAfAAhQL8P8AF4A2j7AZgH4A3A9heA2wHcPgA/AegA9h8ACdB/AF4A7n4AfgPQgf17gAEk/gG4A1x9AM8D6ADY/wAkQJ9fAG4hAXT3t/NoAAAAAElFTkSuQmCC",
    characters: [
      { name: "김민준 대리", position: "마케팅팀", personality: "진지함의 대명사", isVillain: true, visualDescription: "a serious man with glasses and combed black hair", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALdJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
      { name: "이서연 사원", position: "디자인팀", personality: "폰트에 민감한", isVillain: false, visualDescription: "a stylish woman with short bob hair, looking annoyed", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAK9JREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
      { name: "박현우 과장", position: "영업팀", personality: "호탕하고 유쾌한", isVillain: false, visualDescription: "a laughing man with a friendly smile and slightly messy hair", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALZJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
      { name: "최지아 팀장", position: "인사팀", personality: "원칙을 중시하는", isVillain: false, visualDescription: "a woman with her hair in a bun, wearing a sharp blazer, looking stern", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKtJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" }
    ]
  },
  // Set 2: Desktop Wallpaper Sabotage
  {
    sabotage: "누군가 모든 직원의 컴퓨터 바탕화면을 활짝 웃는 CEO의 얼굴 사진으로 통일했습니다.",
    sceneImageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAOJJREFUWEftltENgCAQBD86sR4s1WL9WIs1sAILMIHl7kPIDO7L/w5CWQUYBIyA7cfbA/AdRG3AswE8GgA7wP0bEE8D8QBI5fYA2A+w/wF4aQBsAuw/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4A3gD+s2gPkA7gPAfAAhQL8P8AF4A2j7AZgH4A3A9heA2wHcPgA/AegA9h8ACdB/AF4A7n4AfgPQgf17gAEk/gG4A1x9AM8D6ADY/wAkQJ9fAG4hAXT3t/NoAAAAAElFTkSuQmCC",
    characters: [
      { name: "정다은 사원", position: "IT지원팀", personality: "컴퓨터를 잘 아는", isVillain: false, visualDescription: "a young woman with headphones around her neck, looking knowledgeable", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALdJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
      { name: "윤태영 대리", position: "기획팀", personality: "CEO에게 잘 보이고 싶은", isVillain: true, visualDescription: "a man in a crisp shirt, with an overly enthusiastic smile", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAK9JREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
      { name: "한지민 과장", position: "재무팀", personality: "숫자에 밝고 꼼꼼한", isVillain: false, visualDescription: "a woman with sharp eyes and a calculator on her desk, looking suspicious", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALZJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
      { name: "강동현 부장", position: "총무팀", personality: "느긋하고 여유로운", isVillain: false, visualDescription: "an older man leaning back in his chair with a cup of tea", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKtJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" }
    ]
  },
  // Set 3: Meeting Room Name Sabotage
  {
    sabotage: "누군가 회의실 예약 시스템에 'CEO님과의 비밀 티타임' 같은 가짜 예약을 잔뜩 잡아놓았습니다.",
    sceneImageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAANhJREFUWEftltENgCAQBD86sR4s1WL9WIs1sAILMIHl7kPIDO7L/w5CWQUYBIyA7cfbA/AdRG3AswE8GgA7wP0bEE8D8QBI5fYA2A+w/wF4aQBsAuw/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4A3gD+s2gPkA7gPAfAAhQL8P8AF4A2j7AZgH4A3A9heA2wHcPgA/AegA9h8ACdB/AF4A7n4AfgPQgf17gAEk/gG4A1x9AM8D6ADY/wAkQJ9fAG4hAXT3t/NoAAAAAElFTkSuQmCC",
    characters: [
      { name: "송예리 사원", position: "비서실", personality: "일정이 중요한", isVillain: false, visualDescription: "a woman with a neat ponytail holding a scheduler, looking flustered", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALBJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
      { name: "문성호 대리", position: "개발팀", personality: "장난기가 많은", isVillain: true, visualDescription: "a young man with a mischievous grin and a hoodie", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKpJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
      { name: "오수진 과장", position: "법무팀", personality: "항상 심각한", isVillain: false, visualDescription: "a woman with a stern expression, adjusting her glasses", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALFJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
      { name: "임철민 팀장", position: "영업2팀", personality: "회의를 자주 잡는", isVillain: false, visualDescription: "a man pointing at a chart, looking frustrated", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKhJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" }
    ]
  },
  // Set 4: Wi-Fi Password
  {
    sabotage: "누군가 사무실 와이파이 비밀번호를 'ilovemyboss1234'로 바꿔놓았습니다. 다들 인터넷이 끊겨 당황했습니다.",
    sceneImageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAANFJREFUWEftltENgCAQBD86sR4s1WL9WIs1sAILMIHl7kPIDO7L/w5CWQUYBIyA7cfbA/AdRG3AswE8GgA7wP0bEE8D8QBI5fYA2A+w/wF4aQBsAuw/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4A3gD+s2gPkA7gPAfAAhQL8P8AF4A2j7AZgH4A3A9heA2wHcPgA/AegA9h8ACdB/AF4A7n4AfgPQgf17gAEk/gG4A1x9AM8D6ADY/wAkQJ9fAG4hAXT3t/NoAAAAAElFTkSuQmCC",
    characters: [
        { name: "나희선 사원", position: "IT지원팀", personality: "비밀번호 전문가", isVillain: false, visualDescription: "a woman typing furiously on a laptop, looking determined", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALBJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
        { name: "차범근 대리", position: "기획팀", personality: "아부를 잘하는", isVillain: true, visualDescription: "a man giving a thumbs up with a wide, slightly fake smile", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKpJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
        { name: "유재이 과장", position: "콘텐츠팀", personality: "마감이 급한", isVillain: false, visualDescription: "a woman looking stressed, with messy hair and holding a tablet", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALFJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
        { name: "하동훈 부장", position: "인사팀", personality: "분위기 파악이 빠른", isVillain: false, visualDescription: "a man with crossed arms, looking thoughtfully at the ceiling", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKhJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" }
    ]
  },
  // Set 5: Chair Height
  {
      sabotage: "누군가 모든 사무실 의자의 높이를 최저로 낮춰놓았습니다. 모두가 어린 아이처럼 보입니다.",
      sceneImageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAANlJREFUWEftltENgCAQBD86sR4s1WL9WIs1sAILMIHl7kPIDO7L/w5CWQUYBIyA7cfbA/AdRG3AswE8GgA7wP0bEE8D8QBI5fYA2A+w/wF4aQBsAuw/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4A3gD+s2gPkA7gPAfAAhQL8P8AF4A2j7AZgH4A3A9heA2wHcPgA/AegA9h8ACdB/AF4A7n4AfgPQgf17gAEk/gG4A1x9AM8D6ADY/wAkQJ9fAG4hAXT3t/NoAAAAAElFTkSuQmCC",
      characters: [
          { name: "표민수 사원", position: "디자인팀", personality: "키가 작은 편인", isVillain: true, visualDescription: "a short man who is now at eye-level with his desk, looking pleased", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALZJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
          { name: "왕지현 대리", position: "영업팀", personality: "키가 매우 큰", isVillain: false, visualDescription: "a tall woman whose knees are almost touching her chin, looking uncomfortable", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALdJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
          { name: "길성준 과장", position: "마케팅팀", personality: "허리가 안 좋은", isVillain: false, visualDescription: "a man rubbing his lower back with a pained expression", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAK9JREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
          { name: "엄정화 팀장", position: "고객관리팀", personality: "권위 있는", isVillain: false, visualDescription: "a woman trying to maintain a commanding presence despite her low chair", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKtJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" }
      ]
  },
  // Set 6: Hold Music
  {
      sabotage: "누군가 회사 대표전화의 통화 연결음을 최신 아이돌 댄스곡으로 바꿔놓았습니다.",
      sceneImageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAANFJREFUWEftltENgCAQBD86sR4s1WL9WIs1sAILMIHl7kPIDO7L/w5CWQUYBIyA7cfbA/AdRG3AswE8GgA7wP0bEE8D8QBI5fYA2A+w/wF4aQBsAuw/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4C0AbQBsA+w/gEct4A3gD+s2gPkA7gPAfAAhQL8P8AF4A2j7AZgH4A3A9heA2wHcPgA/AegA9h8ACdB/AF4A7n4AfgPQgf17gAEk/gG4A1x9AM8D6ADY/wAkQJ9fAG4hAXT3t/NoAAAAAElFTkSuQmCC",
      characters: [
          { name: "강미나 사원", position: "총무팀", personality: "흥이 넘치는", isVillain: true, visualDescription: "a young woman subtly dancing at her desk", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALBJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
          { name: "이진욱 대리", position: "해외영업팀", personality: "중요한 전화를 기다리던", isVillain: false, visualDescription: "a man holding a phone receiver with a shocked expression", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKpJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
          { name: "김혜수 과장", position: "홍보팀", personality: "회사의 이미지를 걱정하는", isVillain: false, visualDescription: "a woman with her face in her hands, looking mortified", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAALFJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" },
          { name: "최민식 이사", position: "임원", personality: "클래식 음악을 좋아하는", isVillain: false, visualDescription: "an older, distinguished man looking very displeased with the music", imageUrl: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAKhJREFUWEftlskNwDAQA0+nsRIt1WLtWIu1sAILsIGl3IfI/Hl3/h0ksgr0AkTgbmx9APxGkragXwM4NAD2gPsPYDyAxgGw3R0A+wDuP4BTCbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSAXwG0AbANsP8BPLSA3gB+WLcByAPgDgDuAwhA/D7AB+ANoO0H4DmA3wDbXwBuA3D7APwBoAPg/gEgAP0H4AVw+wH4A0AH9u8BBlDxC8A14PoBPA+gA+D+ByBA/y7AAvgGkF8COD/o/w8AAAAASUVORK5CYII=" }
      ]
  }
];
